spring:
  application:
    name:
      banking-api

  threads:
    virtual:
      enabled: true

#  security:
#    user:
#      name: toilet-cleaner
#      password: 123


  datasource:
    url: jdbc:postgresql://localhost:5432/aft_mobile_banking
    password: qwer
    username: postgres
    driver-class-name: org.postgresql.Driver

#  configure JPA Hibernate DDL
#  DDL = Data Definition Language
#  CREATE, ALTER, RENAME, ...

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
